= Continuous Integration

image:https://jenkins.spring.io/buildStatus/icon?job=spring-data-redis%2Fmaster&subject=Moore%20(master)[link=https://jenkins.spring.io/view/SpringData/job/spring-data-redis/]
image:https://jenkins.spring.io/buildStatus/icon?job=spring-data-redis%2F2.1.x&subject=Lovelace%20(2.1.x)[link=https://jenkins.spring.io/view/SpringData/job/spring-data-redis/]
image:https://jenkins.spring.io/buildStatus/icon?job=spring-data-redis%2F1.8.x&subject=Ingalls%20(1.8.x)[link=https://jenkins.spring.io/view/SpringData/job/spring-data-redis/]

== Running CI tasks locally

Since this pipeline is purely Docker-based, it's easy to:

* Debug what went wrong on your local machine.
* Test out a a tweak to your test routine before sending it out.
* Experiment against a new image before submitting your pull request.

All of these use cases are great reasons to essentially run what the CI server does on your local machine.

IMPORTANT: To do this you must have Docker installed on your machine.

1. `docker run -it --mount type=bind,source="$(pwd)",target=/spring-data-redis-github springci/spring-data-openjdk8-with-redis-5.0:latest /bin/bash`
+
This will launch the Docker image and mount your source code at `spring-data-redis-github`.
+
2. `cd spring-data-redis-github`
+
Next, run the tests from inside the container:
+
3. `./mvnw clean dependency:list test -Dsort -Dbundlor.enabled=false -B` (or with whatever profile you need to test out)

Since the container is binding to your source, you can make edits from your IDE and continue to run build jobs.

If you need to package things up, do this:

1. `docker run -it --mount type=bind,source="$(pwd)",target=/spring-data-redis-github adoptopenjdk/openjdk8:latest /bin/sh`
+
This will launch the Docker image and mount your source code at `spring-data-redis-github`.
+
2. `cd spring-data-redis-github`
+
Next, package things from inside the container doing this:
+
3. `./mvnw clean dependency:list package -Dsort -Dbundlor.enabled=false -B`

NOTE: Docker containers can eat up disk space fast! From time to time, run `docker system prune` to clean out old images.

= Contributing

Here are some ways for you to get involved in the community:

* Get involved with the Spring community on the Stackoverflow. Please help out on the https://stackoverflow.com/questions/tagged/spring-data-redis[spring-data-redis] tag by responding to questions and joining the debate.
* Create https://jira.spring.io/browse/DATAREDIS[JIRA] tickets for bugs and new features and comment and vote on the ones that you are interested in.
* Watch for upcoming articles on Spring by https://spring.io/blog[subscribing] to spring.io.

Before we accept a non-trivial patch or pull request we will need you to https://cla.pivotal.io/sign/spring[sign the Contributor License Agreement]. Signing the contributor’s agreement does not grant anyone commit rights to the main repository, but it does mean that we can accept your contributions, and you will get an author credit if we do. If you forget to do so, you'll be reminded when you submit a pull request.

Github is for social coding: if you want to write code, we encourage contributions through pull requests from https://help.github.com/forking/[forks of this repository]. If you want to contribute code this way, read the Spring Framework https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md[contributor guidelines].
