image:https://spring.io/badges/spring-data-redis/ga.svg[Spring Data Redis,link=https://projects.spring.io/spring-data-redis/#quick-start]
image:https://spring.io/badges/spring-data-redis/snapshot.svg[Spring Data Redis,link=https://projects.spring.io/spring-data-redis/#quick-start]

image:https://jenkins.spring.io/buildStatus/icon?job=spring-data-redis%2Fmaster&subject=Moore%20(master)[link=https://jenkins.spring.io/view/SpringData/job/spring-data-redis/]
image:https://jenkins.spring.io/buildStatus/icon?job=spring-data-redis%2F2.1.x&subject=Lovelace%20(2.1.x)[link=https://jenkins.spring.io/view/SpringData/job/spring-data-redis/]
image:https://jenkins.spring.io/buildStatus/icon?job=spring-data-redis%2F1.8.x&subject=Ingalls%20(1.8.x)[link=https://jenkins.spring.io/view/SpringData/job/spring-data-redis/]

= Spring Data Redis

The primary goal of the https://projects.spring.io/spring-data/[Spring Data] project is to make it easier to build Spring-powered applications that use new data access technologies such as non-relational databases, map-reduce frameworks, and cloud based data services.
This modules provides integration with the https://redis.io/[Redis] store. 

= Docs

You can find out more details from the https://docs.spring.io/spring-data/data-redis/docs/current/reference/html/[user documentation] or by browsing the https://docs.spring.io/spring-data/data-redis/docs/current/api/[javadocs].

= Examples

For examples on using the Spring Data Key Value, see the dedicated project, also available on https://github.com/spring-projects/spring-data-keyvalue-examples[GitHub]

= Artifacts

== Maven configuration

Add the Maven dependency:

[source,xml]
----
<dependency>
  <groupId>org.springframework.data</groupId>
  <artifactId>spring-data-redis</artifactId>
  <version>${version}.RELEASE</version>
</dependency>
----

If you'd rather like the latest snapshots of the upcoming major version, use our Maven snapshot repository and declare the appropriate dependency version.

[source,xml]
----
<dependency>
  <groupId>org.springframework.data</groupId>
  <artifactId>spring-data-redis</artifactId>
  <version>${version}.BUILD-SNAPSHOT</version>
</dependency>

<repository>
  <id>spring-libs-snapshot</id>
  <name>Spring Snapshot Repository</name>
  <url>https://repo.spring.io/libs-snapshot</url>
</repository>
----

== Gradle

[source,groovy]
----
repositories {
   maven { url "https://repo.spring.io/libs-milestone" }
   maven { url "https://repo.spring.io/libs-snapshot" }
}

// used for nightly builds
dependencies {
   compile "org.springframework.data:spring-data-redis:${version}"
}
----

= Usage (for the impatient)

* Configure the Redis connector to use (here https://github.com/xetorthio/jedis[jedis]):
[source,xml]
----
<beans xmlns="http://www.springframework.org/schema/beans"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:p="http://www.springframework.org/schema/p"
  xsi:schemaLocation="
  http://www.springframework.org/schema/beans https://www.springframework.org/schema/beans/spring-beans.xsd">
  
  <bean id="jedisFactory" class="org.springframework.data.redis.connection.jedis.JedisConnectionFactory"/>
  
  <bean id="redisTemplate" class="org.springframework.data.redis.core.RedisTemplate"
      p:connection-factory="jedisFactory"/>
</beans>
----

* Use `RedisTemplate` to interact with the Redis store:
[source,java]
----
String random = template.randomKey();
template.set(random, new Person("John", "Smith"));
----

* Use Redis 'views' to execute specific operations based on the underlying Redis type:
[source,java]
----
ListOperations<String, Person> listOps = template.listOps();
listOps.rightPush(random, new Person("Jane", "Smith"));
List<Person> peopleOnSecondFloor = listOps.range("users:floor:2", 0, -1);
----

= Building

Spring Data Redis uses Maven as its build system.
Running the tests requires you to have a RedisServer running at its default port. Using the `-D runLongTests=true` option executes additional Pub/Sub test.

[source,bash]
----
    mvn clean install
----

You can alternatively use the provided `Makefile` which runs the build plus downloads and spins up the following environment:

* 1 Single Node
* HA Redis (1 Master, 2 Replicas, 3 Sentinels).
* Redis Cluster (3 Masters, 1 Replica)
[source,bash]
----
    make test
----

== Running CI tasks locally

Since this pipeline is purely Docker-based, it's easy to:

* Debug what went wrong on your local machine.
* Test out a a tweak to your test routine before sending it out.
* Experiment against a new image before submitting your pull request.

All of these use cases are great reasons to essentially run what the CI server does on your local machine.

IMPORTANT: To do this you must have Docker installed on your machine.

1. `docker run -it --mount type=bind,source="$(pwd)",target=/spring-data-redis-github springci/spring-data-openjdk8-with-redis-5.0:latest /bin/bash`
+
This will launch the Docker image and mount your source code at `spring-data-redis-github`.
+
2. `cd spring-data-redis-github`
+
Next, run the tests from inside the container:
+
3. `./mvnw clean dependency:list test -Dsort -Dbundlor.enabled=false -B` (or with whatever profile you need to test out)

Since the container is binding to your source, you can make edits from your IDE and continue to run build jobs.

If you need to package things up, do this:

1. `docker run -it --mount type=bind,source="$(pwd)",target=/spring-data-redis-github adoptopenjdk/openjdk8:latest /bin/sh`
+
This will launch the Docker image and mount your source code at `spring-data-redis-github`.
+
2. `cd spring-data-redis-github`
+
Next, package things from inside the container doing this:
+
3. `./mvnw clean dependency:list package -Dsort -Dbundlor.enabled=false -B`

NOTE: Docker containers can eat up disk space fast! From time to time, run `docker system prune` to clean out old images.

= Contributing

Here are some ways for you to get involved in the community:

* Get involved with the Spring community on the Stackoverflow. Please help out on the https://stackoverflow.com/questions/tagged/spring-data-redis[spring-data-redis] tag by responding to questions and joining the debate.
* Create https://jira.spring.io/browse/DATAREDIS[JIRA] tickets for bugs and new features and comment and vote on the ones that you are interested in.
* Watch for upcoming articles on Spring by https://spring.io/blog[subscribing] to spring.io.

Before we accept a non-trivial patch or pull request we will need you to https://cla.pivotal.io/sign/spring[sign the Contributor License Agreement]. Signing the contributor’s agreement does not grant anyone commit rights to the main repository, but it does mean that we can accept your contributions, and you will get an author credit if we do. If you forget to do so, you'll be reminded when you submit a pull request.

Github is for social coding: if you want to write code, we encourage contributions through pull requests from https://help.github.com/forking/[forks of this repository]. If you want to contribute code this way, read the Spring Framework https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md[contributor guidelines].

= Staying in touch

Follow the project team (https://twitter.com/springdata[@SpringData]) on Twitter. In-depth articles can be
found at the Spring https://spring.io/blog[team blog], and releases are announced via our https://spring.io/blog/category/news[news feed].