[[query-by-example.execution]]
== Executing an example

.Query by Example using a Repository
====
[source, java]
----
interface PersonRepository extends QueryByExampleExecutor<Person> {
}

class PersonService {

  @Autowired PersonRepository personRepository;

  List<Person> findPeople(Person probe) {
    return personRepository.findAll(Example.of(probe));
  }
}
----
====

Redis Repositories support with their secondary indexes a subset of Spring Data's Query by Example features.
In particular, only exact, case-sensitive and non-null values are used to construct a query.

Secondary indexes use set-based operations (Set intersection, Set union) to determine matching keys. Adding a property to the query that is not indexed returns no result as no index exists. Query by Example support inspects indexing configuration to only include properties in the query that are covered by an index. This is to prevent accidental inclusion of not indexed properties.

Case-insensitive queries and unsupported ``StringMatcher``s are rejected at runtime.

*Supported Query by Example options*

* Case-sensitive, exact matching of simple and nested properties
* Any/All match modes
* Value transformation of the criteria value
* Exclusion of `null` values from the criteria

*Not supported by Query by Example*

* Case-insensitive matching
* Regex, prefix/contains/suffix String-matching
* Querying of Associations, Collection, and Map-like properties
* Inclusion of `null` values from the criteria
* `findAll` with sorting
